apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: enable-flag
description: 'Enable a Feature Flag'

inputs:
  api_token:
    description: "API token"
    required: false
    default: ""
  app_id:
    description: "The Unify Application ID"
    required: true
  env_id:
    description: "The Unify Environment ID"
    required: true
  flag_id:
    description: "The Unify Feature Flag ID"
    required: true

runs:
  using: composite
  steps:
    - id: enable-flag
      name: Enable Feature Flag
      uses: cloudbees-io/feature-flag-actions/internal/patch-flag@v1
      with:
        api_token: ${{ inputs.api_token }}
        app_id: ${{ inputs.app_id }}
        env_id: ${{ inputs.env_id }}
        flag_id: ${{ inputs.flag_id }}
        payload: '{"enabled":true}'

