= CloudBees Unify Workflow Feature Flag actions

== Actions

[cols="2a,9a",options="header"]
.Input details
|===

| Name
| Description

| link:./enable-flag[enable-flag]
| Enable a Feature Flag in a specific environment

| link:./disable-flag[disable-flag]
| Disable a Feature Flag in a specific environment

|===

== Common Action Inputs

There are a number of action inputs common across the actions in this repo.

=== `api_token`

This is a raw API token value. If not defined, the action will use a secret named `FEATURE_FLAG_ACTIONS_API_TOKEN` or will error.

The easiest way to configure this input for the actions in this repo is to generate an API token and to store it as a secret property named `FEATURE_FLAG_ACTIONS_API_TOKEN` in the appropriate Unify organization/tenant.

=== `app_id`, `flag_id`, and `env_id`

The easiest way to get the values for these inputs is from the link:https://cloudbees.io/[Unify dashboard]. Simply navigate to the Feature Flag configuration page in a browser and use the browser URL as follows.

```
https://cloudbees.io/cloudbees/{app_id}/feature-management/flags/{env_id}/configure?flagId={flag_id}
```