= Patch Feature Flag Config

`PATCH` the configuration of a Feature Flag.

NOTE: This is a low-level action intended to be called by other actions in this repo. For typical use cases prefer link:../../enable-flag[enable-flag] or link:../../disable-flag[disable-flag].

== Inputs

[cols="2a,2a,2a,5a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `api_token`
| String
| No
| The Unify API token. If not defined, the action will use a secret named `FEATURE_FLAG_ACTIONS_API_TOKEN` or will error.

| `app_id`
| String
| Yes
| The Unify application ID with which the Feature Flag is associated.

| `flag_id`
| String
| Yes
| The Feature Flag UUID.

| `env_id`
| String
| Yes
| The Unify environment ID in which the Feature Flag is to be PATCHed.

| `payload`
| String
| Yes
| The JSON payload to PATCH the flag config with e.g. `{"enabled":true}`. See schema below.

|===

=== `payload` schema

[source]
----
{
  "enabled": boolean,
  "defaultValue": any,
  "conditions": [
    array<object>
  ],
  "stickinessProperty": string,
  "variantsEnabled": boolean
}
----

Describing this payload in more detail is beyond scope for now. Easiest way to grok e.g. the `conditions` element is to mimic the desired flag rule config in the link:https://cloudbees.io/[Unify dashboard] and inspect the `PATCH` request payload.

== See Also

* link:../../enable-flag[enable-flag] — Enable a Feature Flag in a specific environment
* link:../../disable-flag[disable-flag] — Disable a Feature Flag in a specific environment
